### ISSUE TITLE
Load Room window vs. Load/Save toolbar buttons

### ISSUE THREAD

**Issue by vtereshkov** [skejeton/savescum#29]
What's the difference?

**Comment by skejeton** [comment]
Not much, "Load" loads the currently loaded room, while Load Room window loads the room in the input prompt. The Save/Load buttons are mostly a workaround until I implement undo/redo.

**Comment by vtereshkov** [comment]
OK, waiting for Undo/Redo then. Anyway, you'll need the Save button somewhere. 

You know, I often refer to the principle of least astonishment. What it tells me here is that, for now, you could have three buttons in a row: Open (which opens the window with a textbox), Save and Reload.

**Comment by skejeton** [comment]
Moving this to undo/redo issue.
