### ISSUE TITLE
Why Player Placer?

### ISSUE THREAD

**Issue by vtereshkov** [skejeton/savescum#30]
Why not use the same entity concept for placing the player (e.g., as an entity with the "player" tag)? A separate window is too much for such a special case.

**Comment by skejeton** [comment]
It's a remnant from the very first version, right now it's mostly a convenience, so you don't have to look for the player in the list, but that would be fixed if I had some sort of search or hierarchy.

**Comment by vtereshkov** [comment]
Yes, I remember it since the first GIF you showed us in July 2022. And its existence has always puzzled me. I'd certainly cut it off with the Occam's razor and implement a sorted entity list instead.

**Comment by skejeton** [comment]
![image](https://github.com/user-attachments/assets/0ec5e90e-ef85-4172-b5a8-18457b9d3901)
It's no more.
