### ISSUE TITLE
Game: I can climb an obstacle 3 blocks high

### ISSUE THREAD

**Issue by vtereshkov** [skejeton/savescum#52]
A bug?

![image](https://github.com/user-attachments/assets/ab8b99cb-30ac-4fe7-baa8-781b51b55a64)

**Comment by skejeton** [comment]
This bug started appearing when I switched to using `sort`. It was very spurious for me, but this one example seems to be reliable. Brb.

**Comment by skejeton** [comment]
There was a typo with `a` and `b`, I used both `a`'s but also the comparison function was wrong.
